/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author HP
 */
public class Horarios_CRUD extends javax.swing.JDialog {

    /**
     * Creates new form Principal
     */
    public Horarios_CRUD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblHorarios = new javax.swing.JTable();
        jcbAsignatura = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jcbCatedratico = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jcbHorarios = new javax.swing.JComboBox<>();
        jcbHoraInicio = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfHoras = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        botCrear = new javax.swing.JButton();
        botActualizar = new javax.swing.JButton();
        botEliminar = new javax.swing.JButton();
        botHome = new javax.swing.JButton();
        botLimpiar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(185, 165, 87));
        jPanel1.setMaximumSize(new java.awt.Dimension(610, 444));
        jPanel1.setMinimumSize(new java.awt.Dimension(610, 444));
        jPanel1.setPreferredSize(new java.awt.Dimension(610, 444));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Asignatura: ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 84, 94, -1));

        jtblHorarios.setBackground(new java.awt.Color(204, 255, 204));
        jtblHorarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtblHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "ASIGNATURA", "CATEDRATICO", "SECCION", "DIAS", "HORA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblHorarios.setGridColor(new java.awt.Color(255, 255, 255));
        jtblHorarios.setSelectionBackground(new java.awt.Color(51, 255, 51));
        jtblHorarios.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtblHorarios);
        if (jtblHorarios.getColumnModel().getColumnCount() > 0) {
            jtblHorarios.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 84, 519, 417));

        jcbAsignatura.setDoubleBuffered(true);
        jcbAsignatura.setFocusable(false);
        jcbAsignatura.setRequestFocusEnabled(false);
        jPanel2.add(jcbAsignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 107, 228, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Catedratico:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 133, 104, -1));

        jcbCatedratico.setDoubleBuffered(true);
        jcbCatedratico.setFocusable(false);
        jcbCatedratico.setRequestFocusEnabled(false);
        jPanel2.add(jcbCatedratico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 156, 228, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Horarios Disponibles: ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 182, -1, -1));

        jcbHorarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes - Jueves", "Viernes", "Sabado", "Domingo" }));
        jcbHorarios.setSelectedIndex(-1);
        jcbHorarios.setDoubleBuffered(true);
        jcbHorarios.setFocusable(false);
        jcbHorarios.setRequestFocusEnabled(false);
        jPanel2.add(jcbHorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 205, 228, -1));

        jcbHoraInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00" }));
        jcbHoraInicio.setDoubleBuffered(true);
        jcbHoraInicio.setFocusable(false);
        jcbHoraInicio.setRequestFocusEnabled(false);
        jPanel2.add(jcbHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 254, 228, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Hora de Inicio: ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 231, 121, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Horario a Asignar: ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jtfHoras.setText(" ");
        jtfHoras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jtfHoras.setEnabled(false);
        jPanel2.add(jtfHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 303, 228, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HORARIOS");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new javax.swing.ImageIcon(getClass().getResource("/imgs/franja.png")))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 238, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logo-uth2.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 11, 226, -1));

        botCrear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/crear.png"))); // NOI18N
        botCrear.setText("CREAR");
        botCrear.setBorderPainted(false);
        botCrear.setContentAreaFilled(false);
        jPanel2.add(botCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 339, 120, 50));

        botActualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/actualizar.png"))); // NOI18N
        botActualizar.setText("ACTUALIZAR");
        botActualizar.setBorderPainted(false);
        botActualizar.setContentAreaFilled(false);
        botActualizar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jPanel2.add(botActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 339, -1, 50));

        botEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/eliminar.png"))); // NOI18N
        botEliminar.setText("ELIMINAR");
        botEliminar.setBorderPainted(false);
        botEliminar.setContentAreaFilled(false);
        jPanel2.add(botEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 399, 130, 50));

        botHome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/home.png"))); // NOI18N
        botHome.setText("HOME");
        botHome.setBorderPainted(false);
        botHome.setContentAreaFilled(false);
        jPanel2.add(botHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 459, 260, 50));

        botLimpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/limpiar.png"))); // NOI18N
        botLimpiar.setText("LIMPIAR");
        botLimpiar.setBorderPainted(false);
        botLimpiar.setContentAreaFilled(false);
        jPanel2.add(botLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 399, 120, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/franja2.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 830, 210));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 20, 830, 520);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/fondo3.jpg"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(0, 0, 880, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Horarios_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Horarios_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Horarios_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Horarios_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Horarios_CRUD dialog = new Horarios_CRUD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botActualizar;
    private javax.swing.JButton botCrear;
    private javax.swing.JButton botEliminar;
    private javax.swing.JButton botHome;
    private javax.swing.JButton botLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbAsignatura;
    private javax.swing.JComboBox<String> jcbCatedratico;
    private javax.swing.JComboBox<String> jcbHoraInicio;
    private javax.swing.JComboBox<String> jcbHorarios;
    private javax.swing.JTable jtblHorarios;
    private javax.swing.JTextField jtfHoras;
    // End of variables declaration//GEN-END:variables
}
